// Code generated by scripts/generate-sdk from openapi/wrappers.yml. DO NOT EDIT.
package roe

import (
	"context"
	"fmt"

	"github.com/roe-ai/roe-golang/generated"
)

// ConnectionsAPI API for managing external data connections.
type ConnectionsAPI struct {
	cfg        Config
	httpClient *httpClient
}

func newConnectionsAPI(cfg Config, httpClient *httpClient) *ConnectionsAPI {
	return &ConnectionsAPI{cfg: cfg, httpClient: httpClient}
}

// List List connections.
func (a *ConnectionsAPI) List(connectorType string, search string, page int, pageSize int) (generated.PaginatedConnectionListList, error) {
	return a.ListWithContext(context.Background(), connectorType, search, page, pageSize)
}

// ListWithContext List connections.
func (a *ConnectionsAPI) ListWithContext(ctx context.Context, connectorType string, search string, page int, pageSize int) (generated.PaginatedConnectionListList, error) {
	query := map[string]string{}
	query["organization_id"] = a.cfg.OrganizationID
	if connectorType != "" {
		query["connector_type"] = fmt.Sprint(connectorType)
	}
	if search != "" {
		query["search"] = fmt.Sprint(search)
	}
	if page != 0 {
		query["page"] = fmt.Sprint(page)
	}
	if pageSize != 0 {
		query["page_size"] = fmt.Sprint(pageSize)
	}
	var resp generated.PaginatedConnectionListList
	if err := a.httpClient.getWithContext(ctx, "/v1/connections/", query, &resp); err != nil {
		return generated.PaginatedConnectionListList{}, err
	}
	return resp, nil
}

// Create Create a connection.
func (a *ConnectionsAPI) Create(connectorType string, name string, config map[string]any, description string, authConfig map[string]any) (generated.Connection, error) {
	return a.CreateWithContext(context.Background(), connectorType, name, config, description, authConfig)
}

// CreateWithContext Create a connection.
func (a *ConnectionsAPI) CreateWithContext(ctx context.Context, connectorType string, name string, config map[string]any, description string, authConfig map[string]any) (generated.Connection, error) {
	query := map[string]string{}
	query["organization_id"] = a.cfg.OrganizationID
	payload := map[string]any{}
	payload["connector_type"] = connectorType
	payload["name"] = name
	payload["config"] = config
	if description != "" {
		payload["description"] = description
	}
	if authConfig != nil {
		payload["auth_config"] = authConfig
	}
	var resp generated.Connection
	if err := a.httpClient.postJSONWithContext(ctx, "/v1/connections/", payload, query, &resp); err != nil {
		return generated.Connection{}, err
	}
	return resp, nil
}

// TestCredentials Test connection credentials without saving a connection.
func (a *ConnectionsAPI) TestCredentials(connectorType string, config map[string]any, authConfig map[string]any) (generated.TestConnection, error) {
	return a.TestCredentialsWithContext(context.Background(), connectorType, config, authConfig)
}

// TestCredentialsWithContext Test connection credentials without saving a connection.
func (a *ConnectionsAPI) TestCredentialsWithContext(ctx context.Context, connectorType string, config map[string]any, authConfig map[string]any) (generated.TestConnection, error) {
	query := map[string]string{}
	payload := map[string]any{}
	payload["connector_type"] = connectorType
	payload["config"] = config
	if authConfig != nil {
		payload["auth_config"] = authConfig
	}
	var resp generated.TestConnection
	if err := a.httpClient.postJSONWithContext(ctx, "/v1/connections/test-credentials/", payload, query, &resp); err != nil {
		return generated.TestConnection{}, err
	}
	return resp, nil
}

// Retrieve Retrieve a connection.
func (a *ConnectionsAPI) Retrieve(connectionID string) (generated.Connection, error) {
	return a.RetrieveWithContext(context.Background(), connectionID)
}

// RetrieveWithContext Retrieve a connection.
func (a *ConnectionsAPI) RetrieveWithContext(ctx context.Context, connectionID string) (generated.Connection, error) {
	query := map[string]string{}
	query["organization_id"] = a.cfg.OrganizationID
	var resp generated.Connection
	if err := a.httpClient.getWithContext(ctx, fmt.Sprintf("/v1/connections/%s/", connectionID), query, &resp); err != nil {
		return generated.Connection{}, err
	}
	return resp, nil
}

// Update Update mutable connection fields.
func (a *ConnectionsAPI) Update(connectionID string, name string, description string, config map[string]any, authConfig map[string]any) (generated.Connection, error) {
	return a.UpdateWithContext(context.Background(), connectionID, name, description, config, authConfig)
}

// UpdateWithContext Update mutable connection fields.
func (a *ConnectionsAPI) UpdateWithContext(ctx context.Context, connectionID string, name string, description string, config map[string]any, authConfig map[string]any) (generated.Connection, error) {
	query := map[string]string{}
	query["organization_id"] = a.cfg.OrganizationID
	payload := map[string]any{}
	if name != "" {
		payload["name"] = name
	}
	if description != "" {
		payload["description"] = description
	}
	if config != nil {
		payload["config"] = config
	}
	if authConfig != nil {
		payload["auth_config"] = authConfig
	}
	var resp generated.Connection
	if err := a.httpClient.patchJSONWithContext(ctx, fmt.Sprintf("/v1/connections/%s/", connectionID), payload, query, &resp); err != nil {
		return generated.Connection{}, err
	}
	return resp, nil
}

// Replace Replace a connection.
func (a *ConnectionsAPI) Replace(connectionID string, name string, description string, config map[string]any, authConfig map[string]any) (generated.Connection, error) {
	return a.ReplaceWithContext(context.Background(), connectionID, name, description, config, authConfig)
}

// ReplaceWithContext Replace a connection.
func (a *ConnectionsAPI) ReplaceWithContext(ctx context.Context, connectionID string, name string, description string, config map[string]any, authConfig map[string]any) (generated.Connection, error) {
	query := map[string]string{}
	query["organization_id"] = a.cfg.OrganizationID
	payload := map[string]any{}
	payload["name"] = name
	payload["description"] = description
	if config != nil {
		payload["config"] = config
	}
	if authConfig != nil {
		payload["auth_config"] = authConfig
	}
	var resp generated.Connection
	if err := a.httpClient.putJSONWithContext(ctx, fmt.Sprintf("/v1/connections/%s/", connectionID), payload, query, &resp); err != nil {
		return generated.Connection{}, err
	}
	return resp, nil
}

// Delete Delete a connection.
func (a *ConnectionsAPI) Delete(connectionID string) error {
	return a.DeleteWithContext(context.Background(), connectionID)
}

// DeleteWithContext Delete a connection.
func (a *ConnectionsAPI) DeleteWithContext(ctx context.Context, connectionID string) error {
	query := map[string]string{}
	query["organization_id"] = a.cfg.OrganizationID
	return a.httpClient.deleteWithContext(ctx, fmt.Sprintf("/v1/connections/%s/", connectionID), query)
}

// Test Test a saved connection.
func (a *ConnectionsAPI) Test(connectionID string) (generated.TestConnection, error) {
	return a.TestWithContext(context.Background(), connectionID)
}

// TestWithContext Test a saved connection.
func (a *ConnectionsAPI) TestWithContext(ctx context.Context, connectionID string) (generated.TestConnection, error) {
	query := map[string]string{}
	query["organization_id"] = a.cfg.OrganizationID
	var resp generated.TestConnection
	if err := a.httpClient.postJSONWithContext(ctx, fmt.Sprintf("/v1/connections/%s/test/", connectionID), nil, query, &resp); err != nil {
		return generated.TestConnection{}, err
	}
	return resp, nil
}
