// Code generated by scripts/generate-sdk from openapi/wrappers.yml. DO NOT EDIT.
package roe

import (
	"context"
	"fmt"

	"github.com/roe-ai/roe-golang/generated"
)

// ConnectorsAPI API for discovering available connector types.
type ConnectorsAPI struct {
	cfg        Config
	httpClient *httpClient
}

func newConnectorsAPI(cfg Config, httpClient *httpClient) *ConnectorsAPI {
	return &ConnectorsAPI{cfg: cfg, httpClient: httpClient}
}

// List List available connector types.
func (a *ConnectorsAPI) List() (generated.ConnectorListResponse, error) {
	return a.ListWithContext(context.Background())
}

// ListWithContext List available connector types.
func (a *ConnectorsAPI) ListWithContext(ctx context.Context) (generated.ConnectorListResponse, error) {
	query := map[string]string{}
	var resp generated.ConnectorListResponse
	if err := a.httpClient.getWithContext(ctx, "/v1/connectors/", query, &resp); err != nil {
		return generated.ConnectorListResponse{}, err
	}
	return resp, nil
}

// Retrieve Retrieve metadata for a connector type.
func (a *ConnectorsAPI) Retrieve(connectorType string) (generated.ConnectorMetadata, error) {
	return a.RetrieveWithContext(context.Background(), connectorType)
}

// RetrieveWithContext Retrieve metadata for a connector type.
func (a *ConnectorsAPI) RetrieveWithContext(ctx context.Context, connectorType string) (generated.ConnectorMetadata, error) {
	query := map[string]string{}
	var resp generated.ConnectorMetadata
	if err := a.httpClient.getWithContext(ctx, fmt.Sprintf("/v1/connectors/%s/", connectorType), query, &resp); err != nil {
		return generated.ConnectorMetadata{}, err
	}
	return resp, nil
}
