// Code generated by scripts/generate-sdk from openapi/wrappers.yml. DO NOT EDIT.
package roe

import (
	"context"

	"github.com/roe-ai/roe-golang/v2/generated"
)

// DiscoveryAPI API for discovering valid agent engine types and model IDs.
type DiscoveryAPI struct {
	cfg        Config
	httpClient *httpClient
}

func newDiscoveryAPI(cfg Config, httpClient *httpClient) *DiscoveryAPI {
	return &DiscoveryAPI{cfg: cfg, httpClient: httpClient}
}

// ListAgentEngineTypes Return production engine_class_id values accepted by agent creation.
func (a *DiscoveryAPI) ListAgentEngineTypes() (generated.AgentEngineTypeList, error) {
	return a.ListAgentEngineTypesWithContext(context.Background())
}

// ListAgentEngineTypesWithContext Return production engine_class_id values accepted by agent creation.
func (a *DiscoveryAPI) ListAgentEngineTypesWithContext(ctx context.Context) (generated.AgentEngineTypeList, error) {
	query := map[string]string{}
	var resp generated.AgentEngineTypeList
	if err := a.httpClient.getWithContext(ctx, "/v1/agents/types/", query, &resp); err != nil {
		return generated.AgentEngineTypeList{}, err
	}
	return resp, nil
}

// ListSupportedModels Return non-deprecated model IDs accepted in engine_config.model.
func (a *DiscoveryAPI) ListSupportedModels(capability string) (generated.SupportedLLMModelList, error) {
	return a.ListSupportedModelsWithContext(context.Background(), capability)
}

// ListSupportedModelsWithContext Return non-deprecated model IDs accepted in engine_config.model.
func (a *DiscoveryAPI) ListSupportedModelsWithContext(ctx context.Context, capability string) (generated.SupportedLLMModelList, error) {
	query := map[string]string{}
	if capability != "" {
		query["capability"] = capability
	}
	var resp generated.SupportedLLMModelList
	if err := a.httpClient.getWithContext(ctx, "/v1/agents/models/", query, &resp); err != nil {
		return generated.SupportedLLMModelList{}, err
	}
	return resp, nil
}
