// Code generated by scripts/generate-sdk from openapi/wrappers.yml. DO NOT EDIT.
package roe

type generatedAPIs struct {
	Discovery *DiscoveryAPI
	Tables *TablesAPI
}

func newGeneratedAPIs(cfg Config, httpClient *httpClient) *generatedAPIs {
	return &generatedAPIs{
		Discovery: newDiscoveryAPI(cfg, httpClient),
		Tables: newTablesAPI(cfg, httpClient),
	}
}
