// Code generated by scripts/generate-sdk from openapi/wrappers.yml. DO NOT EDIT.
package roe

type generatedAPIs struct {
	Connections *ConnectionsAPI
	Connectors  *ConnectorsAPI
	Discovery   *DiscoveryAPI
	Tables      *TablesAPI
}

func newGeneratedAPIs(cfg Config, httpClient *httpClient) *generatedAPIs {
	return &generatedAPIs{
		Connections: newConnectionsAPI(cfg, httpClient),
		Connectors:  newConnectorsAPI(cfg, httpClient),
		Discovery:   newDiscoveryAPI(cfg, httpClient),
		Tables:      newTablesAPI(cfg, httpClient),
	}
}
