// Code generated by scripts/generate-sdk from openapi/wrappers.yml. DO NOT EDIT.
package roe

import (
	"context"
	"fmt"

	"github.com/roe-ai/roe-golang/generated"
)

// SkillSetsAPI Manage skill sets, immutable versions, and generation.
type SkillSetsAPI struct {
	cfg        Config
	httpClient *httpClient
}

func newSkillSetsAPI(cfg Config, httpClient *httpClient) *SkillSetsAPI {
	return &SkillSetsAPI{cfg: cfg, httpClient: httpClient}
}

// List List skill sets.
func (a *SkillSetsAPI) List(ordering string, page int, pageSize int, search string, organizationId string) (generated.PaginatedSkillSetList, error) {
	return a.ListWithContext(context.Background(), ordering, page, pageSize, search, organizationId)
}

// ListWithContext List skill sets.
func (a *SkillSetsAPI) ListWithContext(ctx context.Context, ordering string, page int, pageSize int, search string, organizationId string) (generated.PaginatedSkillSetList, error) {
	query := map[string]string{}
	if ordering != "" {
		query["ordering"] = fmt.Sprint(ordering)
	}
	if page != 0 {
		query["page"] = fmt.Sprint(page)
	}
	if pageSize != 0 {
		query["page_size"] = fmt.Sprint(pageSize)
	}
	if search != "" {
		query["search"] = fmt.Sprint(search)
	}
	if organizationId != "" {
		query["organization_id"] = fmt.Sprint(organizationId)
	}
	var resp generated.PaginatedSkillSetList
	if err := a.httpClient.getWithContext(ctx, "/v1/skills/", query, &resp); err != nil {
		return generated.PaginatedSkillSetList{}, err
	}
	return resp, nil
}

// Create Create a skill set with its initial base version.
func (a *SkillSetsAPI) Create(name string, organizationId string, description string) (generated.CreateSkillSet, error) {
	return a.CreateWithContext(context.Background(), name, organizationId, description)
}

// CreateWithContext Create a skill set with its initial base version.
func (a *SkillSetsAPI) CreateWithContext(ctx context.Context, name string, organizationId string, description string) (generated.CreateSkillSet, error) {
	query := map[string]string{}
	if organizationId != "" {
		query["organization_id"] = fmt.Sprint(organizationId)
	}
	payload := map[string]any{}
	payload["name"] = name
	payload["description"] = description
	var resp generated.CreateSkillSet
	if err := a.httpClient.postJSONWithContext(ctx, "/v1/skills/", payload, query, &resp); err != nil {
		return generated.CreateSkillSet{}, err
	}
	return resp, nil
}

// Retrieve Retrieve skill-set metadata.
func (a *SkillSetsAPI) Retrieve(id string, organizationId string) (generated.SkillSet, error) {
	return a.RetrieveWithContext(context.Background(), id, organizationId)
}

// RetrieveWithContext Retrieve skill-set metadata.
func (a *SkillSetsAPI) RetrieveWithContext(ctx context.Context, id string, organizationId string) (generated.SkillSet, error) {
	query := map[string]string{}
	if organizationId != "" {
		query["organization_id"] = fmt.Sprint(organizationId)
	}
	var resp generated.SkillSet
	if err := a.httpClient.getWithContext(ctx, fmt.Sprintf("/v1/skills/%s/", id), query, &resp); err != nil {
		return generated.SkillSet{}, err
	}
	return resp, nil
}

// Update Update skill-set metadata.
func (a *SkillSetsAPI) Update(id string, organizationId string, name string, description string) (generated.UpdateSkillSet, error) {
	return a.UpdateWithContext(context.Background(), id, organizationId, name, description)
}

// UpdateWithContext Update skill-set metadata.
func (a *SkillSetsAPI) UpdateWithContext(ctx context.Context, id string, organizationId string, name string, description string) (generated.UpdateSkillSet, error) {
	query := map[string]string{}
	if organizationId != "" {
		query["organization_id"] = fmt.Sprint(organizationId)
	}
	payload := map[string]any{}
	if name != "" {
		payload["name"] = name
	}
	payload["description"] = description
	var resp generated.UpdateSkillSet
	if err := a.httpClient.patchJSONWithContext(ctx, fmt.Sprintf("/v1/skills/%s/", id), payload, query, &resp); err != nil {
		return generated.UpdateSkillSet{}, err
	}
	return resp, nil
}

// Delete Delete a skill set and its versions unless referenced by agents.
func (a *SkillSetsAPI) Delete(id string, organizationId string) error {
	return a.DeleteWithContext(context.Background(), id, organizationId)
}

// DeleteWithContext Delete a skill set and its versions unless referenced by agents.
func (a *SkillSetsAPI) DeleteWithContext(ctx context.Context, id string, organizationId string) error {
	query := map[string]string{}
	if organizationId != "" {
		query["organization_id"] = fmt.Sprint(organizationId)
	}
	return a.httpClient.deleteWithContext(ctx, fmt.Sprintf("/v1/skills/%s/", id), query)
}

// GenerateVersion Start asynchronous generation. Pass empty slices for unused tables and attachments.
func (a *SkillSetsAPI) GenerateVersion(skillSetId string, useCase string, organizationId string, baseVersionId string, autoCommit bool, tableNames []string, attachments []string, policyId string, policyVersionId string) (generated.GenerateSkillSetVersionResponse, error) {
	return a.GenerateVersionWithContext(context.Background(), skillSetId, useCase, organizationId, baseVersionId, autoCommit, tableNames, attachments, policyId, policyVersionId)
}

// GenerateVersionWithContext Start asynchronous generation. Pass empty slices for unused tables and attachments.
func (a *SkillSetsAPI) GenerateVersionWithContext(ctx context.Context, skillSetId string, useCase string, organizationId string, baseVersionId string, autoCommit bool, tableNames []string, attachments []string, policyId string, policyVersionId string) (generated.GenerateSkillSetVersionResponse, error) {
	query := map[string]string{}
	if organizationId != "" {
		query["organization_id"] = fmt.Sprint(organizationId)
	}
	payload := map[string]any{}
	payload["use_case"] = useCase
	if baseVersionId != "" {
		payload["base_version_id"] = baseVersionId
	}
	payload["auto_commit"] = autoCommit
	payload["table_names"] = tableNames
	payload["attachments"] = attachments
	if policyId != "" {
		payload["policy_id"] = policyId
	}
	if policyVersionId != "" {
		payload["policy_version_id"] = policyVersionId
	}
	var resp generated.GenerateSkillSetVersionResponse
	if err := a.httpClient.postJSONWithContext(ctx, fmt.Sprintf("/v1/skills/%s/generate-version/", skillSetId), payload, query, &resp); err != nil {
		return generated.GenerateSkillSetVersionResponse{}, err
	}
	return resp, nil
}

// GetGeneration Read the tracked generation, or null when none exists.
func (a *SkillSetsAPI) GetGeneration(skillSetId string, organizationId string) (generated.PublicSkillSetGeneration, error) {
	return a.GetGenerationWithContext(context.Background(), skillSetId, organizationId)
}

// GetGenerationWithContext Read the tracked generation, or null when none exists.
func (a *SkillSetsAPI) GetGenerationWithContext(ctx context.Context, skillSetId string, organizationId string) (generated.PublicSkillSetGeneration, error) {
	query := map[string]string{}
	if organizationId != "" {
		query["organization_id"] = fmt.Sprint(organizationId)
	}
	var resp generated.PublicSkillSetGeneration
	if err := a.httpClient.getWithContext(ctx, fmt.Sprintf("/v1/skills/%s/generation/", skillSetId), query, &resp); err != nil {
		return generated.PublicSkillSetGeneration{}, err
	}
	return resp, nil
}

// CancelGeneration Cancel and stop tracking a generation.
func (a *SkillSetsAPI) CancelGeneration(runId string, skillSetId string, organizationId string) error {
	return a.CancelGenerationWithContext(context.Background(), runId, skillSetId, organizationId)
}

// CancelGenerationWithContext Cancel and stop tracking a generation.
func (a *SkillSetsAPI) CancelGenerationWithContext(ctx context.Context, runId string, skillSetId string, organizationId string) error {
	query := map[string]string{}
	if organizationId != "" {
		query["organization_id"] = fmt.Sprint(organizationId)
	}
	return a.httpClient.deleteWithContext(ctx, fmt.Sprintf("/v1/skills/%s/generation/%s/", skillSetId, runId), query)
}

// SetCurrentVersion Select the current version of a skill set.
func (a *SkillSetsAPI) SetCurrentVersion(skillSetId string, versionId string, organizationId string) (generated.SkillSet, error) {
	return a.SetCurrentVersionWithContext(context.Background(), skillSetId, versionId, organizationId)
}

// SetCurrentVersionWithContext Select the current version of a skill set.
func (a *SkillSetsAPI) SetCurrentVersionWithContext(ctx context.Context, skillSetId string, versionId string, organizationId string) (generated.SkillSet, error) {
	query := map[string]string{}
	if organizationId != "" {
		query["organization_id"] = fmt.Sprint(organizationId)
	}
	var resp generated.SkillSet
	if err := a.httpClient.patchJSONWithContext(ctx, fmt.Sprintf("/v1/skills/%s/set-current-version/%s/", skillSetId, versionId), nil, query, &resp); err != nil {
		return generated.SkillSet{}, err
	}
	return resp, nil
}

// ListVersions List versions of a skill set.
func (a *SkillSetsAPI) ListVersions(skillSetId string, page int, pageSize int, organizationId string) (generated.PaginatedSkillSetVersionList, error) {
	return a.ListVersionsWithContext(context.Background(), skillSetId, page, pageSize, organizationId)
}

// ListVersionsWithContext List versions of a skill set.
func (a *SkillSetsAPI) ListVersionsWithContext(ctx context.Context, skillSetId string, page int, pageSize int, organizationId string) (generated.PaginatedSkillSetVersionList, error) {
	query := map[string]string{}
	if page != 0 {
		query["page"] = fmt.Sprint(page)
	}
	if pageSize != 0 {
		query["page_size"] = fmt.Sprint(pageSize)
	}
	if organizationId != "" {
		query["organization_id"] = fmt.Sprint(organizationId)
	}
	var resp generated.PaginatedSkillSetVersionList
	if err := a.httpClient.getWithContext(ctx, fmt.Sprintf("/v1/skills/%s/versions/", skillSetId), query, &resp); err != nil {
		return generated.PaginatedSkillSetVersionList{}, err
	}
	return resp, nil
}

// CreateVersion Create a complete version and make it current.
func (a *SkillSetsAPI) CreateVersion(skillSetId string, files []map[string]any, organizationId string, versionName string, baseVersionId string, summary string, fileChanges []map[string]any) (generated.CreateSkillSetVersion, error) {
	return a.CreateVersionWithContext(context.Background(), skillSetId, files, organizationId, versionName, baseVersionId, summary, fileChanges)
}

// CreateVersionWithContext Create a complete version and make it current.
func (a *SkillSetsAPI) CreateVersionWithContext(ctx context.Context, skillSetId string, files []map[string]any, organizationId string, versionName string, baseVersionId string, summary string, fileChanges []map[string]any) (generated.CreateSkillSetVersion, error) {
	query := map[string]string{}
	if organizationId != "" {
		query["organization_id"] = fmt.Sprint(organizationId)
	}
	payload := map[string]any{}
	payload["files"] = files
	if versionName != "" {
		payload["version_name"] = versionName
	}
	if baseVersionId != "" {
		payload["base_version_id"] = baseVersionId
	}
	payload["summary"] = summary
	payload["file_changes"] = fileChanges
	var resp generated.CreateSkillSetVersion
	if err := a.httpClient.postJSONWithContext(ctx, fmt.Sprintf("/v1/skills/%s/versions/", skillSetId), payload, query, &resp); err != nil {
		return generated.CreateSkillSetVersion{}, err
	}
	return resp, nil
}

// RetrieveVersion Read a version and its complete file collection.
func (a *SkillSetsAPI) RetrieveVersion(id string, organizationId string) (generated.SkillSetVersion, error) {
	return a.RetrieveVersionWithContext(context.Background(), id, organizationId)
}

// RetrieveVersionWithContext Read a version and its complete file collection.
func (a *SkillSetsAPI) RetrieveVersionWithContext(ctx context.Context, id string, organizationId string) (generated.SkillSetVersion, error) {
	query := map[string]string{}
	if organizationId != "" {
		query["organization_id"] = fmt.Sprint(organizationId)
	}
	var resp generated.SkillSetVersion
	if err := a.httpClient.getWithContext(ctx, fmt.Sprintf("/v1/skills/versions/%s/", id), query, &resp); err != nil {
		return generated.SkillSetVersion{}, err
	}
	return resp, nil
}
