// Code generated by scripts/generate-sdk from openapi/wrappers.yml. DO NOT EDIT.
package roe

import (
	"context"

	"github.com/roe-ai/roe-golang/generated"
)

// TablesAPI API for uploading CSV files into Roe tables.
type TablesAPI struct {
	cfg        Config
	httpClient *httpClient
}

func newTablesAPI(cfg Config, httpClient *httpClient) *TablesAPI {
	return &TablesAPI{cfg: cfg, httpClient: httpClient}
}

// Upload Upload a CSV file and create a Roe table.
func (a *TablesAPI) Upload(tableName string, file FileUpload, withHeaders bool) (generated.TableUploadResponse, error) {
	return a.UploadWithContext(context.Background(), tableName, file, withHeaders)
}

// UploadWithContext Upload a CSV file and create a Roe table.
func (a *TablesAPI) UploadWithContext(ctx context.Context, tableName string, file FileUpload, withHeaders bool) (generated.TableUploadResponse, error) {
	inputs := map[string]any{
		"table_name": tableName,
		"file": file,
		"with_headers": withHeaders,
		"organization_id": a.cfg.OrganizationID,
	}
	var resp generated.TableUploadResponse
	if err := a.httpClient.postDynamicInputsWithContext(ctx, "/v1/tables/upload/", inputs, nil, &resp, nil); err != nil {
		return generated.TableUploadResponse{}, err
	}
	return resp, nil
}
