package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/mod/modfile"
	"gopkg.in/yaml.v3"
)

const (
	readmeBannerStart = "<!-- ROE-SDK:RELEASE-BANNER:START -->"
	readmeBannerEnd   = "<!-- ROE-SDK:RELEASE-BANNER:END -->"
	readmeBlockStart  = "<!-- ROE-SDK:GENERATED-FRIENDLY-APIS:START -->"
	readmeBlockEnd    = "<!-- ROE-SDK:GENERATED-FRIENDLY-APIS:END -->"
)

type contract struct {
	APIs map[string]apiSpec `yaml:"apis"`
}

type apiSpec struct {
	StructName string                   `yaml:"struct_name"`
	FieldName  string                   `yaml:"field_name"`
	Docstring  string                   `yaml:"docstring"`
	Operations []operation              `yaml:"operations"`
	Namespaces map[string]namespaceSpec `yaml:"namespaces"`
}

type namespaceSpec struct {
	StructName string      `yaml:"struct_name"`
	FieldName  string      `yaml:"field_name"`
	Docstring  string      `yaml:"docstring"`
	Operations []operation `yaml:"operations"`
}

type operation struct {
	Kind       string      `yaml:"kind"`
	MethodName string      `yaml:"method_name"`
	Docstring  string      `yaml:"docstring"`
	Method     string      `yaml:"method"`
	Path       string      `yaml:"path"`
	ReturnType string      `yaml:"return_type"`
	BodyType   string      `yaml:"body_type"`
	Parameters []parameter `yaml:"parameters"`

	// body-kind conventions mirrored from the hand-written facades
	InjectOrganizationID bool     `yaml:"inject_organization_id"`
	ErrorWrap            string   `yaml:"error_wrap"`
	SetAPIHook           string   `yaml:"set_api_hook"` // scalar | list | paginated
	RefetchWithRetrieve  bool     `yaml:"refetch_with_retrieve"`
	RefetchCheckEmpty    bool     `yaml:"refetch_check_empty"`
	RefetchExtraArgs     []string `yaml:"refetch_extra_args"`
	Variants             []string `yaml:"variants"`
}

type parameter struct {
	Name             string `yaml:"name"`
	WireName         string `yaml:"wire_name"`
	GoType           string `yaml:"go_type"`
	Location         string `yaml:"location"` // path | query | body (default query)
	Optional         bool   `yaml:"optional"`
	OmitWhenEmpty    bool   `yaml:"omit_when_empty"`
	ValidateNonempty bool   `yaml:"validate_nonempty"`
}

type readmeBlocks struct {
	Blocks struct {
		GeneratedFriendlyAPIs struct {
			Go string `yaml:"go"`
		} `yaml:"generated_friendly_apis"`
	} `yaml:"blocks"`
}

func main() {
	root, err := repoRoot()
	must(err)
	modulePath, err := readModulePath(root)
	must(err)

	spec := readContract(filepath.Join(root, "openapi", "wrappers.yml"))
	must(checkManualParity(root, spec))

	wholeFile := contract{APIs: map[string]apiSpec{}}
	splitNames := []string{}
	for apiName, api := range spec.APIs {
		if specHasManual(api) {
			if specHasGenerated(api) {
				writeSplitAPI(root, apiName, api)
				splitNames = append(splitNames, apiName)
			}
			// all-manual APIs are parity-checked only
			continue
		}
		wholeFile.APIs[apiName] = api
		writeAPI(root, modulePath, apiName, api)
	}
	writeGeneratedAPIs(root, wholeFile)
	syncReadmeReleaseBanner(root)
	syncReadmeBlock(root)
	sort.Strings(splitNames)
	message := fmt.Sprintf("Generated %d friendly API wrapper modules from openapi/wrappers.yml", len(wholeFile.APIs))
	if len(splitNames) > 0 {
		message += fmt.Sprintf(" (+%d split method files: %s)", len(splitNames), strings.Join(splitNames, ", "))
	}
	fmt.Println(message)
}

func specHasManual(api apiSpec) bool {
	for _, op := range api.Operations {
		if op.Kind == "manual" {
			return true
		}
	}
	for _, ns := range api.Namespaces {
		for _, op := range ns.Operations {
			if op.Kind == "manual" {
				return true
			}
		}
	}
	return false
}

func specHasGenerated(api apiSpec) bool {
	for _, op := range api.Operations {
		if op.Kind != "manual" {
			return true
		}
	}
	for _, ns := range api.Namespaces {
		for _, op := range ns.Operations {
			if op.Kind != "manual" {
				return true
			}
		}
	}
	return false
}

// checkManualParity asserts every manual operation still exists as a method in
// the hand-written (non-generated) .go files at the repo root, failing loudly
// with the full list of missing methods.
func checkManualParity(root string, spec contract) error {
	entries, err := os.ReadDir(root)
	if err != nil {
		return err
	}
	var handWritten strings.Builder
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(root, name))
		if err != nil {
			return err
		}
		if bytes.Contains(data, []byte("Code generated by scripts/generate-sdk")) {
			continue
		}
		handWritten.Write(data)
	}
	source := handWritten.String()

	var problems []string
	check := func(scope string, ops []operation) {
		for _, op := range ops {
			if op.Kind != "manual" {
				continue
			}
			if !strings.Contains(source, ") "+op.MethodName+"(") {
				problems = append(problems, fmt.Sprintf(
					"%s: manual operation %q not found (expected a `func (...) %s(` method in a hand-written root .go file)",
					scope, op.MethodName, op.MethodName))
			}
		}
	}
	for _, apiName := range sortedAPINames(spec.APIs) {
		api := spec.APIs[apiName]
		check(apiName, api.Operations)
		nsNames := make([]string, 0, len(api.Namespaces))
		for nsName := range api.Namespaces {
			nsNames = append(nsNames, nsName)
		}
		sort.Strings(nsNames)
		for _, nsName := range nsNames {
			check(apiName+"."+nsName, api.Namespaces[nsName].Operations)
		}
	}
	if len(problems) > 0 {
		return fmt.Errorf("manual wrapper parity check failed:\n  - %s", strings.Join(problems, "\n  - "))
	}
	return nil
}

func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(wd, "go.mod")); err == nil {
			return wd, nil
		} else if !os.IsNotExist(err) {
			return "", err
		}
		parent := filepath.Dir(wd)
		if parent == wd {
			return "", fmt.Errorf("could not find go.mod from %s or any parent directory", wd)
		}
		wd = parent
	}
}

func readModulePath(root string) (string, error) {
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", err
	}
	modulePath := modfile.ModulePath(data)
	if modulePath == "" {
		return "", fmt.Errorf("go.mod must declare a module path")
	}
	return modulePath, nil
}

func readContract(path string) contract {
	data, err := os.ReadFile(path)
	must(err)
	var spec contract
	must(yaml.Unmarshal(data, &spec))
	if len(spec.APIs) == 0 {
		must(fmt.Errorf("%s must contain apis", path))
	}
	return spec
}

func writeGeneratedAPIs(root string, spec contract) {
	var buf bytes.Buffer
	writeHeader(&buf)
	apiNames := sortedAPINames(spec.APIs)

	buf.WriteString("type generatedAPIs struct {\n")
	for _, apiName := range apiNames {
		api := spec.APIs[apiName]
		fmt.Fprintf(&buf, "\t%s *%s\n", api.FieldName, api.StructName)
	}
	buf.WriteString("}\n\n")

	buf.WriteString("func newGeneratedAPIs(cfg Config, httpClient *httpClient) *generatedAPIs {\n")
	buf.WriteString("\treturn &generatedAPIs{\n")
	for _, apiName := range apiNames {
		api := spec.APIs[apiName]
		fmt.Fprintf(&buf, "\t\t%s: new%s(cfg, httpClient),\n", api.FieldName, api.StructName)
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")

	writeFile(root, "generated_apis.go", buf.Bytes())
}

func writeAPI(root, modulePath, apiName string, api apiSpec) {
	var buf bytes.Buffer
	writeHeader(&buf)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	if apiNeedsFmt(api) {
		buf.WriteString("\t\"fmt\"\n")
	}
	buf.WriteString("\n")
	fmt.Fprintf(&buf, "\t%q\n", modulePath+"/generated")
	buf.WriteString(")\n\n")

	fmt.Fprintf(&buf, "// %s %s\n", api.StructName, sentence(api.Docstring))
	fmt.Fprintf(&buf, "type %s struct {\n", api.StructName)
	buf.WriteString("\tcfg        Config\n")
	buf.WriteString("\thttpClient *httpClient\n")
	buf.WriteString("}\n\n")

	fmt.Fprintf(&buf, "func new%s(cfg Config, httpClient *httpClient) *%s {\n", api.StructName, api.StructName)
	fmt.Fprintf(&buf, "\treturn &%s{cfg: cfg, httpClient: httpClient}\n", api.StructName)
	buf.WriteString("}\n\n")

	for index, operation := range api.Operations {
		if index > 0 {
			buf.WriteString("\n")
		}
		switch kind(operation.Kind) {
		case "simple":
			renderSimpleOperation(&buf, api.StructName, operation)
		case "table_upload":
			renderTableUploadOperation(&buf, api.StructName, operation)
		default:
			must(fmt.Errorf("%s.%s has unsupported kind %q", apiName, operation.MethodName, operation.Kind))
		}
	}

	writeFile(root, fmt.Sprintf("%s.go", apiName), buf.Bytes())
}

func renderSimpleOperation(buf *bytes.Buffer, receiver string, op operation) {
	params := goParams(op.Parameters)
	callArgs := goParamNames(op.Parameters)
	if callArgs != "" {
		callArgs = ", " + callArgs
	}

	fmt.Fprintf(buf, "// %s %s\n", op.MethodName, sentence(op.Docstring))
	fmt.Fprintf(buf, "func (a *%s) %s(%s) (%s, error) {\n", receiver, op.MethodName, params, op.ReturnType)
	fmt.Fprintf(buf, "\treturn a.%sWithContext(context.Background()%s)\n", op.MethodName, callArgs)
	buf.WriteString("}\n\n")

	fmt.Fprintf(buf, "// %sWithContext %s\n", op.MethodName, sentence(op.Docstring))
	fmt.Fprintf(buf, "func (a *%s) %sWithContext(ctx context.Context", receiver, op.MethodName)
	for _, param := range op.Parameters {
		fmt.Fprintf(buf, ", %s %s", param.Name, param.GoType)
	}
	fmt.Fprintf(buf, ") (%s, error) {\n", op.ReturnType)
	writeQueryMap(buf, op.Parameters)
	fmt.Fprintf(buf, "\tvar resp %s\n", op.ReturnType)
	fmt.Fprintf(buf, "\tif err := a.httpClient.getWithContext(ctx, %q, query, &resp); err != nil {\n", op.Path)
	fmt.Fprintf(buf, "\t\treturn %s{}, err\n", op.ReturnType)
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn resp, nil\n")
	buf.WriteString("}\n")
}

func renderTableUploadOperation(buf *bytes.Buffer, receiver string, op operation) {
	fmt.Fprintf(buf, "// %s %s\n", op.MethodName, sentence(op.Docstring))
	fmt.Fprintf(buf, "func (a *%s) %s(tableName string, file FileUpload, withHeaders bool) (%s, error) {\n", receiver, op.MethodName, op.ReturnType)
	fmt.Fprintf(buf, "\treturn a.%sWithContext(context.Background(), tableName, file, withHeaders)\n", op.MethodName)
	buf.WriteString("}\n\n")

	fmt.Fprintf(buf, "// %sWithContext %s\n", op.MethodName, sentence(op.Docstring))
	fmt.Fprintf(buf, "func (a *%s) %sWithContext(ctx context.Context, tableName string, file FileUpload, withHeaders bool) (%s, error) {\n", receiver, op.MethodName, op.ReturnType)
	buf.WriteString("\tinputs := map[string]any{\n")
	buf.WriteString("\t\t\"table_name\": tableName,\n")
	buf.WriteString("\t\t\"file\": file,\n")
	buf.WriteString("\t\t\"with_headers\": withHeaders,\n")
	buf.WriteString("\t\t\"organization_id\": a.cfg.OrganizationID,\n")
	buf.WriteString("\t}\n")
	fmt.Fprintf(buf, "\tvar resp %s\n", op.ReturnType)
	fmt.Fprintf(buf, "\tif err := a.httpClient.postDynamicInputsWithContext(ctx, %q, inputs, nil, &resp, nil); err != nil {\n", op.Path)
	fmt.Fprintf(buf, "\t\treturn %s{}, err\n", op.ReturnType)
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn resp, nil\n")
	buf.WriteString("}\n")
}

// receiverCtx carries the expressions a body-kind method needs for a given
// receiver: the parent API struct itself, or a nested namespace struct that
// proxies through its parent (e.g. v.agentsAPI.httpClient).
type receiverCtx struct {
	letter     string
	structName string
	httpExpr   string
	orgExpr    string
	hookExpr   string
}

func parentCtx(apiName string, api apiSpec) receiverCtx {
	letter := apiName[:1]
	return receiverCtx{
		letter:     letter,
		structName: api.StructName,
		httpExpr:   letter + ".httpClient",
		orgExpr:    letter + ".cfg.OrganizationID",
		hookExpr:   letter,
	}
}

func namespaceCtx(apiName, nsName string, ns namespaceSpec) receiverCtx {
	letter := nsName[:1]
	parentField := apiName + "API"
	return receiverCtx{
		letter:     letter,
		structName: ns.StructName,
		httpExpr:   letter + "." + parentField + ".httpClient",
		orgExpr:    letter + "." + parentField + ".cfg.OrganizationID",
		hookExpr:   letter + "." + parentField,
	}
}

// writeSplitAPI emits only the generated METHODS for an API whose struct,
// constructor, namespace wiring, and manual methods stay hand-written.
func writeSplitAPI(root, apiName string, api apiSpec) {
	var methods bytes.Buffer
	needsFmt := false

	render := func(ctx receiverCtx, ops []operation, scope string) {
		for _, op := range ops {
			switch kind(op.Kind) {
			case "body":
				if methods.Len() > 0 {
					methods.WriteString("\n")
				}
				if bodyOperationNeedsFmt(op) {
					needsFmt = true
				}
				renderBodyOperation(&methods, ctx, op)
			case "manual":
				// asserted by checkManualParity; never generated
			default:
				must(fmt.Errorf("%s.%s has unsupported kind %q in a split API", scope, op.MethodName, op.Kind))
			}
		}
	}

	render(parentCtx(apiName, api), api.Operations, apiName)
	nsNames := make([]string, 0, len(api.Namespaces))
	for nsName := range api.Namespaces {
		nsNames = append(nsNames, nsName)
	}
	sort.Strings(nsNames)
	for _, nsName := range nsNames {
		render(namespaceCtx(apiName, nsName, api.Namespaces[nsName]), api.Namespaces[nsName].Operations, apiName+"."+nsName)
	}

	var buf bytes.Buffer
	writeHeader(&buf)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	if needsFmt {
		buf.WriteString("\t\"fmt\"\n")
	}
	buf.WriteString(")\n\n")
	buf.Write(methods.Bytes())

	writeFile(root, fmt.Sprintf("%s_generated.go", apiName), buf.Bytes())
}

func bodyOperationNeedsFmt(op operation) bool {
	if op.ErrorWrap != "" || op.RefetchCheckEmpty {
		return true
	}
	if strings.Contains(op.Path, "{") {
		return true
	}
	for _, p := range op.Parameters {
		if p.ValidateNonempty {
			return true
		}
		if p.Location == "query" || p.Location == "" {
			if p.GoType != "string" || strings.HasPrefix(p.GoType, "*") {
				return true
			}
		}
	}
	return false
}

func pathExpr(op operation) string {
	if !strings.Contains(op.Path, "{") {
		return fmt.Sprintf("%q", op.Path)
	}
	format := op.Path
	for {
		start := strings.Index(format, "{")
		if start < 0 {
			break
		}
		end := strings.Index(format[start:], "}")
		if end < 0 {
			break
		}
		format = format[:start] + "%s" + format[start+end+1:]
	}
	args := []string{}
	for _, p := range op.Parameters {
		if p.Location == "path" {
			args = append(args, p.Name)
		}
	}
	return fmt.Sprintf("fmt.Sprintf(%q, %s)", format, strings.Join(args, ", "))
}

func zeroValue(goType string) string {
	if goType == "" {
		return ""
	}
	if strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "*") || strings.HasPrefix(goType, "map[") {
		return "nil"
	}
	return goType + "{}"
}

func errReturnExpr(op operation, errOnly bool) string {
	if op.ErrorWrap == "" {
		if errOnly {
			return "err"
		}
		return "err"
	}
	count := strings.Count(op.ErrorWrap, "%s")
	args := []string{}
	for _, p := range op.Parameters {
		if p.Location == "path" && len(args) < count {
			args = append(args, p.Name)
		}
	}
	joined := ""
	if len(args) > 0 {
		joined = strings.Join(args, ", ") + ", "
	}
	return fmt.Sprintf("fmt.Errorf(%q, %serr)", op.ErrorWrap+": %w", joined)
}

func renderBodyOperation(buf *bytes.Buffer, ctx receiverCtx, op operation) {
	params := goParams(op.Parameters)
	callArgs := goParamNames(op.Parameters)
	if callArgs != "" {
		callArgs = ", " + callArgs
	}
	retType := op.ReturnType
	errOnly := retType == ""
	zero := zeroValue(retType)
	retSig := "error"
	if !errOnly {
		retSig = fmt.Sprintf("(%s, error)", retType)
	}

	if strings.TrimSpace(op.Docstring) != "" {
		fmt.Fprintf(buf, "// %s %s\n", op.MethodName, sentence(op.Docstring))
	}
	fmt.Fprintf(buf, "func (%s *%s) %s(%s) %s {\n", ctx.letter, ctx.structName, op.MethodName, params, retSig)
	fmt.Fprintf(buf, "\treturn %s.%sWithContext(context.Background()%s)\n", ctx.letter, op.MethodName, callArgs)
	buf.WriteString("}\n\n")

	if strings.TrimSpace(op.Docstring) != "" {
		doc := strings.TrimSuffix(sentence(op.Docstring), ".")
		fmt.Fprintf(buf, "// %sWithContext %s with a caller-supplied context.\n", op.MethodName, doc)
	}
	ctxParams := "ctx context.Context"
	if params != "" {
		ctxParams += ", " + params
	}
	fmt.Fprintf(buf, "func (%s *%s) %sWithContext(%s) %s {\n", ctx.letter, ctx.structName, op.MethodName, ctxParams, retSig)

	// validations
	for _, p := range op.Parameters {
		if !p.ValidateNonempty {
			continue
		}
		fmt.Fprintf(buf, "\tif %s == \"\" {\n", p.Name)
		if errOnly {
			fmt.Fprintf(buf, "\t\treturn fmt.Errorf(\"%s cannot be empty\")\n", p.Name)
		} else {
			fmt.Fprintf(buf, "\t\treturn %s, fmt.Errorf(\"%s cannot be empty\")\n", zero, p.Name)
		}
		buf.WriteString("\t}\n")
	}

	method := strings.ToUpper(op.Method)
	queryParams := []parameter{}
	bodyParams := []parameter{}
	for _, p := range op.Parameters {
		switch p.Location {
		case "body":
			bodyParams = append(bodyParams, p)
		case "path":
		default:
			queryParams = append(queryParams, p)
		}
	}
	injectQueryOrg := op.InjectOrganizationID && method == "GET"
	injectBodyOrg := op.InjectOrganizationID && method != "GET"

	queryArg := "nil"
	if len(queryParams) > 0 || injectQueryOrg {
		queryArg = "params"
		if injectQueryOrg {
			buf.WriteString("\tparams := map[string]string{\n")
			fmt.Fprintf(buf, "\t\t\"organization_id\": %s,\n", ctx.orgExpr)
			buf.WriteString("\t}\n")
		} else {
			buf.WriteString("\tparams := map[string]string{}\n")
		}
		for _, p := range queryParams {
			wire := p.WireName
			if wire == "" {
				wire = p.Name
			}
			switch {
			case strings.HasPrefix(p.GoType, "*bool"):
				fmt.Fprintf(buf, "\tif %s != nil {\n\t\tparams[%q] = fmt.Sprintf(\"%%t\", *%s)\n\t}\n", p.Name, wire, p.Name)
			case p.GoType == "int" && p.OmitWhenEmpty:
				fmt.Fprintf(buf, "\tif %s > 0 {\n\t\tparams[%q] = fmt.Sprintf(\"%%d\", %s)\n\t}\n", p.Name, wire, p.Name)
			case p.GoType == "string" && p.OmitWhenEmpty:
				fmt.Fprintf(buf, "\tif %s != \"\" {\n\t\tparams[%q] = %s\n\t}\n", p.Name, wire, p.Name)
			case p.GoType == "bool":
				fmt.Fprintf(buf, "\tparams[%q] = fmt.Sprintf(\"%%t\", %s)\n", wire, p.Name)
			case p.GoType == "string":
				fmt.Fprintf(buf, "\tparams[%q] = %s\n", wire, p.Name)
			default:
				fmt.Fprintf(buf, "\tparams[%q] = fmt.Sprint(%s)\n", wire, p.Name)
			}
		}
	}

	payloadArg := "nil"
	if len(bodyParams) > 0 || injectBodyOrg {
		payloadArg = "payload"
		required := []parameter{}
		conditional := []parameter{}
		for _, p := range bodyParams {
			if p.OmitWhenEmpty || strings.HasPrefix(p.GoType, "*") {
				conditional = append(conditional, p)
			} else {
				required = append(required, p)
			}
		}
		if len(required) == 0 && !injectBodyOrg {
			buf.WriteString("\tpayload := map[string]any{}\n")
		} else {
			buf.WriteString("\tpayload := map[string]any{\n")
			for _, p := range required {
				wire := p.WireName
				if wire == "" {
					wire = p.Name
				}
				fmt.Fprintf(buf, "\t\t%q: %s,\n", wire, p.Name)
			}
			if injectBodyOrg {
				fmt.Fprintf(buf, "\t\t\"organization_id\": %s,\n", ctx.orgExpr)
			}
			buf.WriteString("\t}\n")
		}
		for _, p := range conditional {
			wire := p.WireName
			if wire == "" {
				wire = p.Name
			}
			if strings.HasPrefix(p.GoType, "*") {
				fmt.Fprintf(buf, "\tif %s != nil {\n\t\tpayload[%q] = *%s\n\t}\n", p.Name, wire, p.Name)
			} else {
				fmt.Fprintf(buf, "\tif %s != \"\" {\n\t\tpayload[%q] = %s\n\t}\n", p.Name, wire, p.Name)
			}
		}
	}

	path := pathExpr(op)
	errExpr := errReturnExpr(op, errOnly)

	if op.RefetchWithRetrieve {
		buf.WriteString("\tvar respID struct {\n\t\tID string `json:\"id\"`\n\t}\n")
		fmt.Fprintf(buf, "\tif err := %s.postJSONWithContext(ctx, %s, %s, nil, &respID); err != nil {\n", ctx.httpExpr, path, payloadArg)
		fmt.Fprintf(buf, "\t\treturn %s, %s\n\t}\n", zero, errExpr)
		if op.RefetchCheckEmpty {
			buf.WriteString("\tif respID.ID == \"\" {\n")
			fmt.Fprintf(buf, "\t\treturn %s, fmt.Errorf(\"unexpected response: missing version ID\")\n\t}\n", zero)
		}
		refetchArgs := []string{}
		for _, p := range op.Parameters {
			if p.Location == "path" {
				refetchArgs = append(refetchArgs, p.Name)
			}
		}
		refetchArgs = append(refetchArgs, "respID.ID")
		refetchArgs = append(refetchArgs, op.RefetchExtraArgs...)
		fmt.Fprintf(buf, "\treturn %s.RetrieveWithContext(ctx, %s)\n", ctx.letter, strings.Join(refetchArgs, ", "))
		buf.WriteString("}\n")
		return
	}

	verbCall := ""
	respArg := "&resp"
	if errOnly {
		respArg = "nil"
	}
	switch method {
	case "GET":
		verbCall = fmt.Sprintf("%s.getWithContext(ctx, %s, %s, %s)", ctx.httpExpr, path, queryArg, respArg)
	case "POST":
		verbCall = fmt.Sprintf("%s.postJSONWithContext(ctx, %s, %s, nil, %s)", ctx.httpExpr, path, payloadArg, respArg)
	case "PUT":
		verbCall = fmt.Sprintf("%s.putJSONWithContext(ctx, %s, %s, nil, %s)", ctx.httpExpr, path, payloadArg, respArg)
	case "DELETE":
		verbCall = fmt.Sprintf("%s.deleteWithContext(ctx, %s, %s)", ctx.httpExpr, path, queryArg)
	default:
		must(fmt.Errorf("operation %s has unsupported method %q", op.MethodName, op.Method))
	}

	if errOnly {
		if op.ErrorWrap == "" {
			fmt.Fprintf(buf, "\treturn %s\n", verbCall)
		} else {
			fmt.Fprintf(buf, "\tif err := %s; err != nil {\n\t\treturn %s\n\t}\n\treturn nil\n", verbCall, errExpr)
		}
		buf.WriteString("}\n")
		return
	}

	fmt.Fprintf(buf, "\tvar resp %s\n", retType)
	fmt.Fprintf(buf, "\tif err := %s; err != nil {\n\t\treturn %s, %s\n\t}\n", verbCall, zero, errExpr)
	switch op.SetAPIHook {
	case "scalar":
		fmt.Fprintf(buf, "\tresp.setAgentsAPI(%s)\n", ctx.hookExpr)
	case "list":
		fmt.Fprintf(buf, "\tfor i := range resp {\n\t\tresp[i].setAgentsAPI(%s)\n\t}\n", ctx.hookExpr)
	case "paginated":
		fmt.Fprintf(buf, "\tfor i := range resp.Results {\n\t\tresp.Results[i].setAgentsAPI(%s)\n\t}\n", ctx.hookExpr)
	case "":
	default:
		must(fmt.Errorf("operation %s has unsupported set_api_hook %q", op.MethodName, op.SetAPIHook))
	}
	buf.WriteString("\treturn resp, nil\n")
	buf.WriteString("}\n")
}

func writeQueryMap(buf *bytes.Buffer, params []parameter) {
	buf.WriteString("\tquery := map[string]string{}\n")
	for _, param := range params {
		wireName := param.WireName
		if wireName == "" {
			wireName = param.Name
		}
		if param.OmitWhenEmpty {
			condition, err := omitWhenEmptyCondition(param)
			must(err)
			fmt.Fprintf(buf, "\tif %s {\n", condition)
			fmt.Fprintf(buf, "\t\tquery[%q] = fmt.Sprint(%s)\n", wireName, param.Name)
			buf.WriteString("\t}\n")
		} else {
			fmt.Fprintf(buf, "\tquery[%q] = fmt.Sprint(%s)\n", wireName, param.Name)
		}
	}
}

func omitWhenEmptyCondition(param parameter) (string, error) {
	switch param.GoType {
	case "string":
		return fmt.Sprintf("%s != \"\"", param.Name), nil
	case "bool":
		return param.Name, nil
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64":
		return fmt.Sprintf("%s != 0", param.Name), nil
	default:
		return "", fmt.Errorf("%s has omit_when_empty with unsupported go_type %q", param.Name, param.GoType)
	}
}

func apiNeedsFmt(api apiSpec) bool {
	for _, op := range api.Operations {
		if len(op.Parameters) > 0 {
			return true
		}
	}
	return false
}

func goParams(params []parameter) string {
	// Group consecutive same-type parameters (Go shorthand: `a, b string`),
	// matching the hand-written facades' style.
	parts := []string{}
	group := []string{}
	for i, param := range params {
		group = append(group, param.Name)
		if i == len(params)-1 || params[i+1].GoType != param.GoType {
			parts = append(parts, strings.Join(group, ", ")+" "+param.GoType)
			group = nil
		}
	}
	return strings.Join(parts, ", ")
}

func goParamNames(params []parameter) string {
	names := make([]string, 0, len(params))
	for _, param := range params {
		names = append(names, param.Name)
	}
	return strings.Join(names, ", ")
}

func syncReadmeBlock(root string) {
	data, err := os.ReadFile(filepath.Join(root, "openapi", "readme_blocks.yml"))
	must(err)
	var blocks readmeBlocks
	must(yaml.Unmarshal(data, &blocks))
	block := strings.TrimSpace(blocks.Blocks.GeneratedFriendlyAPIs.Go)
	if block == "" {
		must(fmt.Errorf("openapi/readme_blocks.yml must contain blocks.generated_friendly_apis.go"))
	}

	readmePath := filepath.Join(root, "README.md")
	readmeBytes, err := os.ReadFile(readmePath)
	must(err)
	readme := string(readmeBytes)
	updated := replaceMarkedBlock(readme, readmeBlockStart, readmeBlockEnd, block)
	must(os.WriteFile(readmePath, []byte(updated), 0o644))
}

func syncReadmeReleaseBanner(root string) {
	version := readTrimmed(filepath.Join(root, "VERSION"))
	marker := readTrimmed(filepath.Join(root, ".roe-main-release-version"))
	block := fmt.Sprintf(`> **v%s** - Schema synchronization across roe-python / roe-typescript /
> roe-golang. This release is generated from SDK OpenAPI marker %s, and
> all public package metadata is bumped to %s. No Go module import-path
> migration; the SDK stays on %s.`,
		version,
		"`"+marker+"`",
		version,
		"`github.com/roe-ai/roe-golang`",
	)

	readmePath := filepath.Join(root, "README.md")
	readmeBytes, err := os.ReadFile(readmePath)
	must(err)
	readme := string(readmeBytes)
	updated := replaceMarkedBlock(readme, readmeBannerStart, readmeBannerEnd, block)
	must(os.WriteFile(readmePath, []byte(updated), 0o644))
}

func replaceMarkedBlock(readme, startMarker, endMarker, block string) string {
	start := strings.Index(readme, startMarker)
	end := strings.Index(readme, endMarker)
	if start < 0 || end < start {
		must(fmt.Errorf("README.md must contain %s and %s", startMarker, endMarker))
	}
	end += len(endMarker)
	return readme[:start] + startMarker + "\n" + strings.TrimSpace(block) + "\n" + endMarker + readme[end:]
}

func readTrimmed(path string) string {
	data, err := os.ReadFile(path)
	must(err)
	value := strings.TrimSpace(string(data))
	if value == "" {
		must(fmt.Errorf("%s must not be empty", path))
	}
	return value
}

func writeHeader(buf *bytes.Buffer) {
	buf.WriteString("// Code generated by scripts/generate-sdk from openapi/wrappers.yml. DO NOT EDIT.\n")
	buf.WriteString("package roe\n\n")
}

func writeFile(root, relpath string, data []byte) {
	if strings.HasSuffix(relpath, ".go") {
		formatted, err := format.Source(data)
		if err != nil {
			must(fmt.Errorf("gofmt %s: %w", relpath, err))
		}
		data = formatted
	}
	must(os.WriteFile(filepath.Join(root, relpath), data, 0o644))
}

func sortedAPINames(apis map[string]apiSpec) []string {
	names := make([]string, 0, len(apis))
	for name := range apis {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func kind(value string) string {
	if value == "" {
		return "simple"
	}
	return value
}

func sentence(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "wraps a generated Roe API operation."
	}
	if strings.HasSuffix(value, ".") {
		return value
	}
	return value + "."
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
